from typing import List, Literal
from pydantic import BaseModel, Field

class Visualization(BaseModel):
    """Describes a single data visualization plot."""
    title: str = Field(..., description="A clear, business-focused title for the visualization that explains what it shows.")
    file_path: str = Field(..., description="The exact file path where the plot was saved, e.g., 'visualizations/avg_price_over_time.png'.")
    business_insight: str = Field(..., description="A concise, 1-2 sentence explanation of the key business insight revealed by this visualization.")

class VisualizationReport(BaseModel):
    """A structured report containing a list of all generated data visualizations and their insights."""
    visualizations: List[Visualization] = Field(..., description="A list containing exactly 10 visualizations generated by the agent.")